replicaCount: 1
image:
  repository: myazuredevopsprac.azurecr.io/helmjava
  tag: 35
  imagePullPolicy: IfNotPresent
service:
  enabled: true
  type: LoadBalancer
  port: 80
  targetPort: 8080
  protocol: TCP
