{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-890-data-exchange-service
  labels:
      spring-boot: "true"
  annotations:
          service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "30"
spec:
  selector:
    app: {{ .Release.Name | quote }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.targetPort }}
    - name: https
      port: 443
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
{{- end }}
